### ISSUE TITLE
Configure plugin for Azure Databricks

### ISSUE THREAD

**Issue by asantos2000** [mullerpeter/databricks-grafana#16]
Could you provide an example of the plugin's configuration with Azure Databricks?

According to the [documentation](https://learn.microsoft.com/en-us/azure/databricks/sql/api/sql-endpoints), the endpoint path is deprecated, but still working.

I can't configure the plugin, it returns a 404

<img width="1015" alt="Screen Shot 2023-03-10 at 14 39 54" src="https://user-images.githubusercontent.com/1181358/224385691-f59ef3ae-631a-475c-926c-af2bced8b790.png">

I have success calling the API

curl -X GET --header "Authorization: Bearer $DATABRICKS_TOKEN" \
https://adb-1234567890123456.12.azuredatabricks.net/api/2.0/sql/warehouses/778d6587b7d84780

**Comment by mullerpeter** [comment]
`Server Hostname` & `HTTP Path` should be the same as in the connection details of the SQL Warehouse. This works for me on Azure Databricks.

The SQL Warehouses APIs 2.0 is used to configure SQL warehouses and not to issue queries to my knowledge.

![CleanShot 2023-03-10 at 18 51 23@2x](https://user-images.githubusercontent.com/6986867/224389226-0317802a-9ad2-4429-bb13-e31e154c691d.png)
