### ISSUE TITLE
Enable Trino plugin with Alerting capability 

### ISSUE THREAD

**Issue by Amit-Hora** [mullerpeter/databricks-grafana#24]
@mullerpeter  Any chance we can use this great work to enrich Grafana-trino plugin with alert feature ?

https://github.com/trinodb/grafana-trino

I don't know where to get started to enable alert support but I guess it shld be same as the databricks plugin alert support 

Thanks

**Comment by mullerpeter** [comment]
Just need to set the alerting flag to `true` in the [plugin.json](https://github.com/mullerpeter/databricks-grafana/blob/d8d65ed448b149f424f361610f71a14354113960/src/plugin.json#L9). (See[ Grafana Documentation](https://grafana.com/docs/grafana/latest/developers/plugins/metadata/))
