### ISSUE TITLE
HTTP Proxy Support

### ISSUE THREAD

**Issue by shmyer** [mullerpeter/databricks-grafana#3]
Does the plugin currently support HTTP Proxies? We tried running Grafana with the following environment variables:

- HTTP_PROXY
- HTTPS_PROXY
- http_proxy
- https_proxy

But the connection to Databricks always timed out as direct access is blocked by our firewall.

**Comment by mullerpeter** [comment]
I don't think HTTP proxies are supported at the moment. The plugin uses the [databricks-sql-go ](https://github.com/databricks/databricks-sql-go) library to connect to Databricks, which as far as I can see it does not support HTTP proxies so far. 

A related issue has been raised in the databricks-sql-python package https://github.com/databricks/databricks-sql-python/issues/22

**Comment by shmyer** [comment]
Thanks for the information. We worked around this now by allowing direct access to Databricks in our Firewall.
