### ISSUE TITLE
Invalid SessionHandle: SessionHandle

### ISSUE THREAD

**Issue by ChristianWr** [mullerpeter/databricks-grafana#6]
After running for a while having refresh every x minutes I ran into Invalid SessionHandle error. Is there a way to cathc this error and reinitiate a new session?

**Comment by mullerpeter** [comment]
Hey @ChristianWr, you're right the DB connection expires after some time, leading to the Invalid SessionHandle error. 
I added a temp fix for now (#7). 

The fix is not optimal since it opens a new connection on each query, but should work for now while I search for a better solution.
