### ISSUE TITLE
Issue when working with "All-purpose compute"

### ISSUE THREAD

**Issue by udiazulayintel** [mullerpeter/databricks-grafana#61]
Hi,

When i work with "SQL Serverless compute" - all works well.

when i switch to "All-purpose compute" cluster (based on it's configuration definition) it sometimes connects and most of the time i get this error : 

Status: 500. Message: databricks: execution error: failed to execute query: Invalid SessionHandle: SessionHandle [9a5f4e58-4dd7-4f24-888b-cccc4ba43435]
(Trace ID: 5750f2cba6944b4692e930476b85be84)

BUT - if i go back to the data sources settings, and "save" it again, then go back to the dashboard, it work...

**Comment by mullerpeter** [comment]
This issue has been happening for quite some time, I thought it was fixed by #28 but does not look like it. I reintroduced the connection refresh logic on that particular error now.

Try v1.2.3 and see if that solves your issue.

**Comment by udiazulayintel** [comment]
Thanks much!

Thanks,
Udi
