### ISSUE TITLE
Multi SQL query with a variable definition 

### ISSUE THREAD

**Issue by ronnykober** [mullerpeter/databricks-grafana#90]
**Is your feature request related to a problem? Please describe.**
We want to use SQL variables in Databricks SQL, to use dynamic column names direct in the SQL-Query from the panel. But it seems that the SQL connect don't support SQL variables.

![garfana_databricks](https://github.com/user-attachments/assets/3a7753a3-de4a-45c9-b0a8-8b395c5948c1)

**Describe the solution you'd like**
I can use Multi-SQL-query for a panel.

**Describe alternatives you've considered**
The alternative is to use Grafana variables for that, this is possible but the startup of the dashboard took a long time. Because the content of the variables are loaded from databricks. And the complexity is higher, because I have logic in the variables and in the panel. 

**Additional context**
we use
* grafana 10.4.5 
* plugin version 1.3.0.

**Comment by mullerpeter** [comment]
Hi @ronnykober 

Thanks for opening the issue! The [1.3.1 Release](https://github.com/mullerpeter/databricks-grafana/releases/tag/v1.3.1) fixes the issue and setting variables in multi statement queries is working now.
