### ISSUE TITLE
[Bug] The required field 'scope' is missing when using OAuth2 Client credentials

### ISSUE THREAD

**Issue by Koliham** [mullerpeter/databricks-grafana#99]
I have the OAuth2 credentials to get access tokens from Microsoft for Databricks. I tried the credentials via curl and it works:

```
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' \
https://login.microsoftonline.com/123456789/oauth2/v2.0/token \
-d 'client_id=1234567890' \
-d 'grant_type=client_credentials' \
-d 'scope=1234567890.default' \
-d 'client_secret=12345678'
```
and I get a typical response:
`{"token_type":"Bearer","expires_in":3599,"ext_expires_in":3599,"access_token":"eyabcdefg"}`

But when I type in the credentials into the UI fields of Databricks:
![image](https://github.com/user-attachments/assets/3a75f0bd-a989-48b7-8e11-bc5fb7909ffe)
I get an error:
`oauth2: "invalid_request" "AADSTS90014: The required field 'scope' is missing from the credential.`
I can reproduce this error in the curl command, when I omit the scope value.

So is there a way to pass the 'scope' field?

**Comment by mullerpeter** [comment]
Hey @Koliham 

Thanks for opening the issue. I added support to set the scopes for the OAuth Flow. 
As I don't have an endpoint at hand to test it, could you try the pre-release [v1.3.4-rc.1](https://github.com/mullerpeter/databricks-grafana/releases/tag/v1.3.4-rc.1) and report back to me if that works for you. I'll then merge it.

Thank you :)

**Comment by mullerpeter** [comment]
@Koliham I was able to test this now.

Configuring the default Azure Databricks scope `2ff814a6-3304-4ab8-85cb-cd0e6f879c1d/.default` and OAuth2 Endpoint `https://login.microsoftonline.com/{tenant-id}/oauth2/v2.0/token` in the datasource plugin settings, now correctly returns a valid token and allows the plugin to authenticate with Databricks. 

Release [v1.3.4](https://github.com/mullerpeter/databricks-grafana/releases/tag/v1.3.4) should fix your issue.

**Comment by Koliham** [comment]
Yes it works now, thanks a lot!
